### ISSUE TITLE
HttpClient Interception fails on Windows 10 build 1803

### ISSUE THREAD

**Issue by ppittle** [ppittle/HttpWebRequestWrapper#25]
HttpClient interception **fails** on Windows 10 build **1803** and can be seen by these tests failing:

https://github.com/ppittle/HttpWebRequestWrapper/blob/c946a4dd89dbef161fb1f86fe1d0fa4361ab8290/src/HttpWebRequestWrapper.Tests/HttpClientTests.cs#L19

with:

```
System.Net.Http.HttpRequestException
An error occurred while sending the request.
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HttpWebRequestWrapper.Tests.HttpClientTests.<CanInterceptAndSpoofResponse>d__4.MoveNext() in C:\Projects\SkyKick\HttpWebRequestWrapper\src\HttpWebRequestWrapper.Tests\HttpClientTests.cs:line 129

System.Net.WebException
The remote name could not be resolved: 'fakesite.fake'
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
```

Confirmed tests **pass** on Windows 10 build **1607**.

What the hell did Microsoft change?

**Comment by ppittle** [comment]
It appears the Windows 10 build 1803 includes code changes to `HttpClientWrapper` that potentially nullify my interception strategy:

| Build 1607 (working) | Build 1803 (failing) |
| -----------------------|----------------------|
| `Task.Factory.StartNew(this.startRequest, (object) state); ` | ` Task.Run((Action) (() => this._startRequest((object) state)));`|

Change occurred in System.Net.Http.dll.  Version `4.7.2661.0` works.  Version `4.7.3056.0` (Win 10 build 1803) breaks.
